# Default experiment configurations
default_experiments:
  - name: "ngram_baseline"
    model: "ngram"
    description: "Baseline n-gram model with default parameters"
    params:
      match_threshold: 0.75
      min_ngram_size: 2
      max_ngram_size: 4

  - name: "basic_baseline"
    model: "basic"
    description: "Basic rule-based model with default parameters"
    params: {}

  - name: "sparse_baseline"
    model: "sparse"
    description: "High-precision sparse explicit model for first-layer filtering"
    params: {}

# Experiment sets for different scenarios
experiment_sets:
  precision_focused:
    - name: "ngram_high_precision"
      model: "ngram"
      description: "N-gram model tuned for higher precision"
      params:
        match_threshold: 0.85
        min_ngram_size: 3
        max_ngram_size: 5
    
    - name: "basic_strict"
      model: "basic"
      description: "Basic model with stricter matching"
      params:
        score_threshold: 0.8

    - name: "sparse_strict"
      model: "sparse"
      description: "Sparse explicit model with very high precision"
      params:
        confidence_threshold: 0.9
        require_structural_context: true

  recall_focused:
    - name: "ngram_high_recall"
      model: "ngram"
      description: "N-gram model optimized for recall"
      params:
        match_threshold: 0.65
        min_ngram_size: 2
        max_ngram_size: 6
    
    - name: "basic_relaxed"
      model: "basic"
      description: "Basic model with relaxed thresholds"
      params:
        score_threshold: 0.6

    - name: "sparse_relaxed"
      model: "sparse"
      description: "Sparse explicit model with relaxed matching"
      params:
        confidence_threshold: 0.7
        require_structural_context: false

  combined:
    - name: "ngram_balanced"
      model: "ngram"
      description: "N-gram model with balanced precision/recall"
      params:
        match_threshold: 0.75
        min_ngram_size: 2
        max_ngram_size: 5
    
    - name: "basic_balanced"
      model: "basic"
      description: "Basic model with balanced thresholds"
      params:
        score_threshold: 0.7

    - name: "sparse_balanced"
      model: "sparse"
      description: "Sparse explicit model with balanced settings"
      params:
        confidence_threshold: 0.8
        require_structural_context: true 