paths:
  default:
    train: "data/merged/train_enriched.csv"
    test: "data/merged/test_enriched.csv"
    validation: "preprocessed_validation_set.csv"
    output: "experiments"

  windows:
    train: "C:/Users/shil6369/cultural-law-interpretations/immigration_fine_tuning/data/merged/train_enriched.csv"
    test: "C:/Users/shil6369/cultural-law-interpretations/immigration_fine_tuning/data/merged/test_enriched.csv"
    validation: "preprocessed_validation_set.csv"
    output: "experiments" 